### ISSUE TITLE
Should the -c --clipboard option be the default?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [fabianmoronzirfas/to-markdown-cli#1]

**Comment by gwpantazes** [comment]
It surprised me that the tool didn't take stdin when I piped in a `curl` to a web page.

I'd say, if there's some way to detect it, if the tool is getting something from STDIN, then STDIN should be used.
If the user isn't piping anything and but they have something on their clipboard, then sure, the clipboard could be the fallback in that scenario.

But yeah, just popping in to say that not accepting STDIN was a bit of a shock.

**Comment by fabianmoronzirfas** [comment]
Yeah. It should. Maybe I Dufke some time in the next days. PRs welcome

**Comment by fabianmoronzirfas** [comment]
Accepts STDIN now v0.4.1
